from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class BrowserSession(Protocol):
    async def goto(self, url: str) -> None: ...
    async def click(self, selector: str) -> None: ...
    async def scroll(self, amount: int | None = None) -> None: ...
    async def screenshot(self) -> bytes: ...
    async def get_html(self) -> str: ...
    async def get_visible_text(self) -> str: ...
    async def evaluate_js(self, script: str) -> Any: ...
    async def wait_for_network_idle(self) -> None: ...
    async def current_url(self) -> str: ...
